---
openapi: 3.0.1
info:
  title: API Portfolio
  version: v1
  description: Documentação da API do portfólio técnico com autenticação JWT
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []
paths:
  "/api/profile":
    get:
      summary: Retorna o usuário autenticado
      tags:
      - Profile
      security:
      - bearerAuth: []
      responses:
        '200':
          description: usuário autenticado
        '401':
          description: sem token
  "/api/projects":
    get:
      summary: Lista todos os projetos do usuário autenticado
      tags:
      - Projects
      security:
      - bearerAuth: []
      parameters:
      - name: tech
        in: query
        required: false
        description: Nome da tecnologia
        schema:
          type: string
      - name: page
        in: query
        required: false
        description: Número da página
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        description: Resultados por página
        schema:
          type: integer
      responses:
        '200':
          description: projetos listados
    post:
      summary: Cria um novo projeto
      tags:
      - Projects
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: projeto criado com sucesso
        '401':
          description: não autenticado
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: string
        required: true
  "/api/projects/{id}":
    patch:
      summary: Atualiza um projeto existente
      tags:
      - Projects
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: projeto atualizado com sucesso
        '404':
          description: projeto não encontrado
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: string
    delete:
      summary: Remove um projeto existente
      tags:
      - Projects
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: projeto deletado com sucesso
        '404':
          description: projeto não encontrado
